name = "mailer"
target = "javascript"
version = "1.0.0"

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"
lustre = "~> 4.0"
simplifile = "~> 1.5"
xmleam = ">= 1.1.5 and < 2.0.0"
birl = ">= 1.6.1 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
