name = "mailer"
target = "javascript"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.40.0 and < 1.0.0"
gleam_json = ">= 3.0.1 and < 4.0.0"
# xmleam = ">= 1.1.5 and < 2.0.0"
xmleam = {git = "git@github.com:tovedetered/xmleam.git", ref = "3f2f0a144dc81fdf7e95bc11c8766629c21046c1"}
birl = ">= 1.6.1 and < 2.0.0"
midas = ">= 1.0.0 and < 2.0.0"
lustre = ">= 5.2.1 and < 6.0.0"
midas_sdk = ">= 0.4.1 and < 1.0.0"
plinth = ">= 0.5.5 and < 1.0.0"
midas_node = ">= 1.3.0 and < 2.0.0"
netlify = {path = "../../mono-2024/midas_sdk/sdks/netlify"}
at_protocol = {path = "../../mono-2024/midas_sdk/sdks/at_protocol"}
gleam_javascript = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 1.7.0 and < 3.0.0"
snag = ">= 1.1.0 and < 2.0.0"
spotless = ">= 2.0.0 and < 3.0.0"
email_octopus = {path = "../../mono-2024/midas_sdk/sdks/email_octopus"}
gleam_http = ">= 4.0.0 and < 5.0.0"
oas_generator_utils = ">= 1.0.0 and < 2.0.0"
weekly = { path = "../server" }

[dev-dependencies]
gleeunit = "~> 1.0"
